import { boardHex, maxExp, nibbleGrid, type Tile } from '../game/logic';
import type { NftReward, TxEntry } from '../game/useGame';
import { DIR_ARROWS, DIR_NAMES, NFT_THRESHOLD } from '../data/contract';
import { fmtInt, fmtNum } from '../hooks/useBaseChain';
import { ActionButton } from './ui';

const TILE_COLORS: [string, string][] = [
  ['#101d3d', '#101d3d'],
  ['#182a52', '#9fb4e0'],
  ['#203a6e', '#c2d1f3'],
  ['#1447b8', '#dce8ff'],
  ['#0052ff', '#ffffff'],
  ['#2f7dff', '#ffffff'],
  ['#00b3e6', '#042633'],
  ['#00c2b0', '#04302b'],
  ['#ffb03a', '#3a2400'],
  ['#ff8f2e', '#401f00'],
  ['#ff6a2e', '#ffffff'],
  ['#ffd76a', '#3d2a00'],
  ['#ff4d6d', '#ffffff'],
];

function StatBox({ label, value, accent }: { label: string; value: string; accent?: boolean }) {
  return (
    <div className="rounded-xl border border-line bg-panel px-4 py-3 text-center">
      <p className="text-[11px] font-medium text-slate-500 mb-1">{label}</p>
      <p className={`font-display text-2xl leading-none ${accent ? 'text-amber' : 'text-white'}`}>{value}</p>
    </div>
  );
}

function NftCard({
  score,
  tiles,
  nft,
  nftLifetime,
  onchainNft,
}: {
  score: number;
  tiles: Tile[];
  nft: NftReward | null;
  nftLifetime: number;
  onchainNft?: { id: number; image: string | null; link: string | null } | null;
}) {
  const nibbles = nibbleGrid(tiles);
  const minted = Boolean(nft) || Boolean(onchainNft && onchainNft.id > 0);
  const progress = Math.min(100, (score / NFT_THRESHOLD) * 100);
  const oc = onchainNft && onchainNft.id > 0 ? onchainNft : null;

  return (
    <div
      className={`relative overflow-hidden rounded-2xl p-5 ${
        minted ? 'nft-frame' : 'border border-gold/25 bg-panel'
      }`}
    >
      <div className="flex items-center justify-between mb-4">
        <p className="flex items-center gap-2 text-xs text-slate-400">
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#ffd76a" strokeWidth="2">
            <path d="M12 2 3 7v10l9 5 9-5V7l-9-5Z" strokeLinejoin="round" />
          </svg>
          NFT trophy — ERC-721 <span className="font-mono text-gold">O2048</span>
        </p>
        <span className="rounded-md bg-gold/15 px-2 py-1 font-mono text-[10px] text-gold">
          {nftLifetime > 0 ? `${nftLifetime} minted` : 'not earned yet'}
        </span>
      </div>

      <div className="grid grid-cols-[96px_1fr] items-center gap-4">
        {oc?.image ? (
          <div className="overflow-hidden rounded-xl border border-gold/50 bg-[#0a0f24]">
            <img src={oc.image} alt="On-chain trophy" className="block w-full" />
          </div>
        ) : (
          <div className={`rounded-xl border p-1.5 transition-colors ${minted ? 'border-gold/50 bg-[#0a0f24]' : 'border-line/70 bg-ink'}`}>
            <div className="grid grid-cols-4 gap-[3px]">
              {nibbles.map((n, i) => {
                const [bg, fg] = TILE_COLORS[Math.min(n, 12)] ?? ['#101d3d', '#101d3d'];
                return (
                  <div
                    key={i}
                    className="flex aspect-square items-center justify-center rounded-[4px] font-mono text-[8.5px] font-bold transition-colors duration-300"
                    style={{ background: bg, color: fg }}
                  >
                    {n > 0 ? 2 ** n : ''}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {minted ? (
          <div className="min-w-0">
            <p className="font-display text-2xl text-gold leading-none mb-1.5">
              {nft?.simulated ? 'SIMULATED' : `TOKEN #${oc ? oc.id : nft?.tokenId}`}
            </p>
            {nft?.simulated ? (
              <p className="text-[11px] leading-5 text-slate-400">
                Demo only — no on-chain transaction was sent. Connect a wallet on Base and cross{' '}
                <span className="font-display text-gold">{fmtInt(NFT_THRESHOLD)}</span> to mint the real trophy.
              </p>
            ) : nft?.hash ? (
              <p className="font-mono text-[10px] text-slate-400 leading-5 break-all">{nft.hash.slice(0, 26)}…</p>
            ) : (
              <p className="font-mono text-[10px] text-slate-400 leading-5">minted on-chain</p>
            )}
            {oc?.link && (
              <a href={oc.link} target="_blank" rel="noreferrer" className="mt-1 inline-block font-mono text-[10px] text-cyan-bright underline-offset-2 hover:underline">
                View on Basescan ↗
              </a>
            )}
            <p className="mt-2 text-[11px] leading-5 text-slate-500">
              Board frozen on-chain · SVG metadata generated by <span className="font-mono text-cyan-bright">tokenURI()</span>
            </p>
          </div>
        ) : (
          <div className="min-w-0">
            <p className="text-[13px] leading-6 text-slate-400">
              Cross <span className="font-display text-gold">{fmtInt(NFT_THRESHOLD)}</span> points and the contract mints
              you a one-of-one trophy with this exact board frozen into its SVG.
            </p>
            <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-ink">
              <div
                className="h-full rounded-full bg-gradient-to-r from-base via-cyan-bright to-gold transition-all duration-500"
                style={{ width: `${progress}%` }}
              />
            </div>
            <p className="mt-1.5 font-mono text-[10px] text-slate-500">
              {fmtInt(score)} / {fmtInt(NFT_THRESHOLD)}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

export function SidePanel({
  score,
  best,
  moves,
  tiles,
  lastGain,
  txs,
  nft,
  nftLifetime,
  canUndo,
  liveBlock,
  onchain,
  explorer,
  onchainNft,
  onRestart,
  onUndo,
}: {
  score: number;
  best: number;
  moves: number;
  tiles: Tile[];
  lastGain: { value: number; key: number } | null;
  txs: TxEntry[];
  nft: NftReward | null;
  nftLifetime: number;
  canUndo: boolean;
  liveBlock: number;
  onchain?: boolean;
  explorer?: string | null;
  onchainNft?: { id: number; image: string | null; link: string | null } | null;
  onRestart: () => void;
  onUndo: () => void;
}) {
  const hex = boardHex(tiles);
  const nibbles = nibbleGrid(tiles);

  return (
    <div className="flex h-full flex-col gap-4">
      {/* score */}
      <div className="relative overflow-hidden rounded-2xl border border-line bg-panel p-5">
        <div className="flex items-start justify-between">
          <div>
            <p className="text-xs text-slate-500 mb-1">Score</p>
            <p className="font-display text-5xl text-white leading-none">{fmtInt(score)}</p>
            {lastGain && lastGain.value > 0 && (
              <span key={lastGain.key} className="gain-float font-display text-xl text-mint" dir="ltr">
                +{fmtInt(lastGain.value)}
              </span>
            )}
          </div>
          <div className="text-right">
            <p className="text-xs text-slate-500 mb-1">Best</p>
            <p className="font-display text-2xl text-amber leading-none">{fmtInt(best)}</p>
          </div>
        </div>
        <div className="mt-4 grid grid-cols-2 gap-3">
          <StatBox label="Moves" value={fmtInt(moves)} />
          <StatBox label="Largest tile" value={fmtNum(2 ** maxExp(tiles))} accent />
        </div>
        <div className="mt-4 flex gap-3">
          <ActionButton onClick={onRestart} className="flex-1">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4">
              <path d="M3 12a9 9 0 1 0 3-6.7M3 4v5h5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            New run
          </ActionButton>
          <ActionButton variant="ghost" onClick={onUndo} disabled={!canUndo || onchain} className="flex-1">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4">
              <path d="M9 14 4 9l5-5M4 9h10a6 6 0 0 1 0 12h-3" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            Undo
          </ActionButton>
        </div>
      </div>

      {/* NFT trophy */}
      <NftCard score={score} tiles={tiles} nft={nft} nftLifetime={nftLifetime} onchainNft={onchainNft} />

      {/* controls */}
      <div className="rounded-2xl border border-line bg-panel p-5">
        <p className="text-xs text-slate-500 mb-3">
          Controls — every move is a <span className="font-mono text-cyan-bright" dir="ltr">move(dir)</span> transaction
        </p>
        <div className="flex items-center justify-between">
          <div className="flex flex-col items-center gap-1.5" dir="ltr">
            <span className="keycap">↑</span>
            <div className="flex gap-1.5">
              <span className="keycap">←</span>
              <span className="keycap">↓</span>
              <span className="keycap">→</span>
            </div>
          </div>
          <p className="text-[12px] leading-6 text-slate-400 max-w-[46%]">
            Arrow keys or <span className="font-mono text-slate-300">WASD</span> — swipe on mobile.
          </p>
        </div>
      </div>

      {/* tx log */}
      <div className="rounded-2xl border border-line bg-panel p-5 flex-1 min-h-[180px]">
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs text-slate-500">Recent transactions</p>
          <span className="flex items-center gap-1.5 text-[10px] text-slate-500">
            <span className={`h-1.5 w-1.5 rounded-full ${onchain ? 'bg-mint pulse-dot' : liveBlock > 0 ? 'bg-mint' : 'bg-amber'}`} />
            {onchain ? 'on-chain · real txs' : liveBlock > 0 ? 'live simulation' : 'local simulation'}
          </span>
        </div>
        {txs.length === 0 ? (
          <p className="text-[13px] text-slate-600 leading-7">
            No moves yet. Push any direction and its transaction lands right here.
          </p>
        ) : (
          <ul className="space-y-2">
            {txs.map((tx) => {
              const isNft = tx.kind === 'nft';
              const isStart = tx.kind === 'start';
              const hashNode = explorer ? (
                <a href={`${explorer}/tx/${tx.hash}`} target="_blank" rel="noreferrer" className="text-slate-300 underline-offset-2 hover:text-cyan-bright hover:underline">
                  {tx.hash.slice(0, 10)}…
                </a>
              ) : (
                <span>{tx.hash.slice(0, 10)}…</span>
              );
              return (
                <li
                  key={tx.id}
                  className={`tx-row flex items-center justify-between gap-2 rounded-lg border px-3 py-2 ${
                    isNft ? 'border-gold/40 bg-gold/[0.06]' : isStart ? 'border-amber/40 bg-amber/[0.05]' : 'border-line/60 bg-ink'
                  }`}
                >
                  <div className="flex items-center gap-2 min-w-0">
                    {isNft ? (
                      <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-gold/20 text-gold">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4">
                          <path d="M12 2 3 7v10l9 5 9-5V7l-9-5Z" strokeLinejoin="round" />
                        </svg>
                      </span>
                    ) : isStart ? (
                      <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-amber/20 font-mono text-xs text-amber">Ξ</span>
                    ) : (
                      <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-base/15 font-mono text-xs text-base-bright" dir="ltr">
                        {DIR_ARROWS[tx.dir ?? 0]}
                      </span>
                    )}
                    <div className="min-w-0" dir="ltr">
                      <p className="font-mono text-[11px] text-slate-300">
                        {isNft ? `mint trophy #${tx.tokenId}` : isStart ? 'start()' : `move(${tx.dir})`} · {hashNode}
                      </p>
                      <p className="font-mono text-[10px] text-slate-600">
                        block {fmtNum(tx.block)} · {fmtNum(Number(tx.gas))} gas
                      </p>
                    </div>
                  </div>
                  <div className="text-left shrink-0" dir="ltr">
                    {isNft ? (
                      <span className="font-display text-sm text-gold">NFT</span>
                    ) : isStart ? (
                      <span className="font-mono text-[10px] text-amber">free</span>
                    ) : tx.gained > 0 ? (
                      <span className="font-display text-sm text-mint">+{fmtInt(tx.gained)}</span>
                    ) : (
                      <span className="font-mono text-[10px] text-slate-600">{DIR_NAMES[tx.dir ?? 0]}</span>
                    )}
                  </div>
                </li>
              );
            })}
          </ul>
        )}
      </div>

      {/* storage snapshot */}
      <div className="rounded-2xl border border-line bg-panel p-5" dir="ltr">
        <p className="text-[11px] text-slate-500 mb-3" dir="rtl">
          The board as one <span className="font-mono text-cyan-bright">uint64</span> — exactly like contract storage
        </p>
        <div className="grid grid-cols-4 gap-1.5 mb-3">
          {nibbles.map((n, i) => (
            <div
              key={i}
              className={`flex h-9 items-center justify-center rounded-md font-mono text-xs transition-colors ${
                n > 0 ? 'bg-base/15 text-base-bright' : 'bg-ink text-slate-700'
              }`}
            >
              {n.toString(16).toUpperCase()}
            </div>
          ))}
        </div>
        <p className="break-all rounded-lg bg-ink px-3 py-2 font-mono text-[11px] leading-5 text-mint/80">{hex}</p>
      </div>
    </div>
  );
}
